### ISSUE TITLE
Angriffs runde 

### ISSUE THREAD

**Issue by taioo** [tpe-lecture/exercises#2]
welche der zwei  runden varianten ist richtig?

![neue bitmap](https://cloud.githubusercontent.com/assets/14871128/10758079/58b3f694-7caf-11e5-8d2d-d3aaaef1429f.jpg)

maximal 4 Anführer
- jeder Anführer Rase wird nur einmal hinzugefügt oder öfter ?

**Comment by Lubitzkie** [comment]
Erst greifen alle Figuren von Spieler 1 (z.B. der Reihe nach) eine zufällige Figur von Spieler 2 an.
Dann greifen alle Figuren von Spieler 2 eine zufällige Figur von Spieler 1 an.

**Comment by taioo** [comment]
Ok danke
