### ISSUE TITLE
Exercise 4 - Finanzamt

### ISSUE THREAD

**Issue by Dan1194** [tpe-lecture/exercises#3]
Wenn das Finanzamt lediglich alle steuerpflichtigen Einwohner kennt, aber nicht die Syndikate und Unternehmen, welche auch Steuern zahlen, dann kann das Finanzamt nicht die gesamten Steuereinnahmen von Metropolis berechnen.

**Comment by BreBad38** [comment]
Hi,
du hast dich wohl an der matrikelnr verwechselt, hab dir keine Frage gestellt. Sorry bro Versuchs woanders. 

gruß Ilker 1428038


Von meinem iPhone gesendet

**Comment by 1423444** [comment]
@Dan1194 Gute Frage. Assign mal den Prof auf das Issue. Würde mich auch interessieren.
@thomsmits
